### ISSUE TITLE
should Values implement #to_hash?

### ISSUE THREAD

**Issue by michaelglass** [tcrayford/Values#60]
Using this gem, I've noticed implicit type coercion (via `to_hash`) exposing the `hash` attribute in lots of places (e.g. through `ActiveSupport`'s `as_json`. From reading https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html I'd guess that this Library should impliment `to_hash`

Curious if there's any objection, else will open a PR.

In the mean time, here's a hacky monkeypatch:

https://gist.github.com/michaelglass/b702603f4d02ffbd16cfc884896e44dd

**Comment by ms-ati** [comment]
Hi @michaelglass, I do have an objection, I'm afraid. Per [the link above](https://zverok.github.io/blog/2016-01-18-implicit-vs-expicit.html):

> Longer version is implicit conversion:
> 
> * your type should implement it only if it sees itself as “kind of” target type (“better” or “specialized” number, string, array, hash);
> * you should call those methods on incoming data, if you have strict requirement for it being of target type, but want to check it in Ruby way, with duck typing, not class comparison;
> * you should not implement and use this methods in other cases!

Classes created with the Values gem **do not** see themselves, by default, as "kind of" a `Hash`. Is this a surprise or an area where others see it differently?

Therefore, it seems appropriate to provide the **explicit** short method (`#to_h`), but not the implicit long method (`#to_hash`).

Within a Rails app, would it not make more sense to try one of these alternative approaches?

1. Call `my_value_instance.to_h.to_json`
2. Define the `alias_method :to_hash, :to_h` on your Value class, rather than **all** Value classes
3. Create a module which defines this alias, and include or extend your value classes with it?

The reason I'm opposed to saying that all Value objects see themselves as a "kind of" Hash is exactly for the reasons specified in that blog post -- we don't want strange things happening as a result of innocent value objects being misinterpreted as hashes in unexpected places.

**Comment by michaelglass** [comment]
I buy that.

I've been using `Values` as a generic immutable data store but really what I want is an immutable hash rather than say an immutable struct.
